# Variables, Objects and Expressions

## Object Type and Type Conversion

### The Type of an Object

By now, we know that an assignment like $x = 2$ triggers the creation of an object by the name $x$. That object will be of *type* `int` and have the value 2. 

Similarly, the assignment $y = 2.0$ will generate an object named $y$, with value 2.0 and type `float`, since real numbers like 2.0 are called *floating point numbers* in computer language (by the way, note that floats in Python are often written with just a trailing “dot”, e.g., 2. in stead of 2.0). 

We have also learned that when Python interprets, e.g., $s$ = ‘This is a string’, it stores the text (in between the quotes) in an object of type `str` named $s$. These object types, i.e., `int`, `float` and `str`, are still just a few of the many built-in object types in Python.



### The Type Function 

There is a useful built-in function type that can be used to check the type of an object:

In [1]:
x =2

y = 4.0

s = 'hello'


In [2]:
type(x)

int

In [3]:
type(y)

float

In [4]:
type(s)

str

### Type Conversion

Objects may be converted from one type to another if it makes sense. If, e.g., $x$ is the name of an `int` object, writing

In [5]:
x = 1
y = float(x)
y

1.0

show that $y$ then becomes a floating point representation of $x$. Similarly, writing

In [6]:
x = 1.0
y = int(x)
y

1

illustrates that $y$ becomes an integer representation of x. Note that the int function rounds down, e.g., $y$ = int(1.9) also makes $y$ become the integer 1. Type conversion may also occur automatically.

## Automatic Type Conversion

- What if we add a float object to an int object?

- Adding two strings?

- A string + an integer?....

-  Python is a *dynamically type language*
-  Python is also a *strongly typed language*

In [7]:
x = 2

x = x + 4.0

x

6.0

In [8]:
z = 10               # z refers to an integer

z = 10.0             # z refers to a float

z = 'some string'    # z refers to a string

In [9]:
'yes' + 'no'         # add two strings

'yesno'

In [10]:
'yes' + 10           # ... try adding string and integer

TypeError: can only concatenate str (not "int") to str

## Operator Precedence

When the arithmetic operators $+, -, *, /$ and $**$ appear in an expression, Python gives them a certain precedence. Python interprets the expression from left to right, taking one term (part of expression between two successive $+$ or $-$) at a time. Within each term, $**$ is done before $*$ and $/$.

Consider the expression $x = 1*5**2 + 10*3 - 1.0/4$. There are three terms here and interpreting this, Python starts from the left. In the first term, $1*5**2$, it first does $5**2$ which equals 25. This is then multiplied by 1 to give 25 again. The second term is $10*3$, i.e., 30. So the first two terms add up to 55. The last term gives 0.25, so the final result is 54.75 which becomes the value of $x$.

## Division--- Quotient and Remainder

It is sometimes desirable to pick out the quotient and remainder of a division $\frac{a}{b}$
for integer or floating point numbers $a$ and $b$. In Python, we can do this with the operators $//$ (*integer division*) and $\%$ (*modulo*), respectively. They have the same precedence as $*$, and their use may be exemplified by

In [11]:
11//2

5

In [12]:
11%2

1

Note that the sign of the remainder follows the sign of the denominator, i.e.,

In [13]:
-11%2

1

In [14]:
11%-2

-1

## Using Parentheses

Note that parentheses are often very important to group parts of expressions together in the intended way. Let us consider some variable $x$ with the value 4 and assume that you want to divide 1.0 by $x + 1$. We know the answer is 0.2, but the way we present the task to Python is critical, as shown by the following example.

In [15]:
x=4

1.0/x+1

1.25

In [16]:
1.0/(x+1)

0.2

## Round-off Errors

Since most numbers can be represented only approximately on the computer, this gives rise to what is called *rounding* errors. We may illustrate this if we take a look at the previous calculation in more detail. 

In [17]:
x  = 4

y = 1.0/(x+1)

print('The value of y is: {:.17f}'.format(y))


The value of y is: 0.20000000000000001


So, what should have been exactly 0.2, is really a slightly different value! The inexact number representation gave us a small error. Usually, such errors are so small compared to the other numbers of the calculation, that we do not need to bother with them. Still, keep it in mind, since you will encounter this issue from time to time. 

## Boolean Expressions

In programming, we often need to check whether something is true or not true, and then take action accordingly. This is handled by use of *logical* or *boolean expressions*, which evaluate to the *Boolean values* true or false (i.e., not true). In Python, these values are written `True` and `False`, respectively (note capital letters T and F!).

In [18]:
x = 4
# The following is a series of boolean expressions:

x > 5        # x greater than 5

False

In [19]:
x >= 5      # x greater than, or equal to, 5

False

In [20]:
x < 5       # x smaller than 5

True

In [21]:
x <= 5     # x smaller than, or equal to, 5

True

In [22]:
x == 4    # x equal to 4

True

In [23]:
x != 4     # x not equal to 4  

False

In [24]:
x == 5 or x == 4      # x equal to 5 OR x equal to 4

True

In [25]:
not x == 4           # not x equal to 4

False

# Numerical Python Arrays

The arrays will be of *type* `numpy.ndarray`, referred to as N-dimensional arrays in **NumPy**.

Arrays are created and treated according to certain rules, and as a programmer, you may direct Python to compute and handle arrays as a whole, or as individual array *elements*. All array elements must be of the same type, e.g., all integers or all floating point numbers.

## Array Creation and Array Elements

We saw previously how the `linspace` function from numpy could be used to generate an array of evenly distributed numbers from an interval $[a, b]$. As a quick reminder, we may interactively create an array $x$ with three real numbers, evenly distributed on $[0, 2]$:


In [26]:
from numpy import linspace

x = linspace(0, 2, 3)

x

array([0., 1., 2.])

In [27]:
type(x)

numpy.ndarray

In [28]:
type(x[0])

numpy.float64

In [29]:
sum_elements = x[0] + x[1] + x[2]

sum_elements

3.0

In [30]:
product_2_elements = x[1]*x[2]

product_2_elements

2.0

In [31]:
x[0] = 5.0      # overwrite previous values

x

array([5., 1., 2.])

### The Zeros Function

There are other common ways to generate arrays too. One way is to use another `numpy` function named `zeros`, which (as the name suggests) may be used to produce an array with zeros. These zeros can be either floating point numbers or integers, depending on the arguments provided when `zeros` is called. Often, the zeros are overwritten in a second step to arrive at an array with the numbers actually wanted.


### The Built-In Len Function

It is appropriate here to also mention the built-in function `len`, which is useful when you need to find the length (i.e., the number of elements) of an array.

A quick demonstration of `zeros` and `len` may go like this

In [32]:
from numpy import zeros

x = zeros(3, int)            # get array with integer zeros
x

array([0, 0, 0])

In [33]:
y = zeros(3)               # get zrray with floating point zeros
y

array([0., 0., 0.])

In [34]:
y[0] = 0.0;  y[1] = 1.0; y[2] = 2.0     # overwrite
y

array([0., 1., 2.])

In [35]:
len(y)

3

### The Array Function

Another handy way of creating an array, is by using the function `array`, e.g., like this,

In [36]:
from numpy import array

x = array([0, 1, 2])     # get array with integers

x

array([0, 1, 2])

In [37]:
x = array([0., 1., 2.]) # get array with real numbers

x

array([0., 1., 2.])

Note the use of "dots" to get floating point numbers and that we call array with bracketed numbers, i.e., $[0, 1, 2]$  and $[0., 1., 2.]$

## Indexing an Array from the End

By use of a minus sign, the elements of an array may be indexed from the end, rather from the beginning. That is, with our array $x$ here, we could get hold of the very last element by writing $x[-1]$, the second last element by writing $x[-2]$, and so on. Continuing the previous interactive session, we may write

In [38]:
x[-1]

2.0

In [39]:
x[-2]

1.0

In [40]:
x[-3]

0.0

In [41]:
x[-3]

0.0

## Copying an Array

Copying arrays requires some care, as can be seen next, when we try to make a copy of the x array from above:

In [42]:
y = x 

y

array([0., 1., 2.])

In [43]:
y[0] = 10.0

y

array([10.,  1.,  2.])

In [44]:
x

array([10.,  1.,  2.])

Intuitively, it may seem very strange that changing an element in $y$ causes a similar changein $x$! The thingis,however,that our assignment $y = x$ does *not* make a copy of the x array. Rather, Python creates another reference, named $y$, to the same array object that $x$ refers to. That is, there is one array object with two names ($x$ and $y$). Therefore, changing either $x$ or $y$, simultaneously changes “the other” (note that this behavior differs from what we found for single integer, float or string objects).

To really get a copy that is decoupled from the original array, you may use the copy function from numpy,

In [45]:
from numpy import copy

x = linspace(0, 2, 3)    # x becomes array([0., 1., 2.])

y = copy(x)

y

array([0., 1., 2.])

In [46]:
y[0] = 10.0

y

array([10.,  1.,  2.])

In [47]:
x

array([0., 1., 2.])

## Slicing an Array

By use of a colon, you may work with a *slice* of an array. For example, by writing $x[i:j]$, we address all elements from index $i$ (inclusive) to $j$ (exclusive) in an array $x$. An interactive session illustrates this,

In [48]:
from numpy import linspace

x = linspace(11, 16, 6)

x

array([11., 12., 13., 14., 15., 16.])

In [49]:
y = x[1:5]

y

array([12., 13., 14., 15.])

In [50]:
y[0] = -1.0

y

array([-1., 13., 14., 15.])

In [51]:
x

array([11., -1., 13., 14., 15., 16.])

## Two-Dimensional Arrays and Matrix Computations

To calculate with matrices, we need arrays with more than one “dimension”. Such arrays may be generated in different ways, for example by use of the same `zeros` function that we have seen before, it just has to be called a bit differently. Let us illustrate by doing a simple matrix-vector multiplication with the numpy function `dot`:

In [52]:
import numpy as np

I = np.zeros((3, 3))   # create matrix (note parentheses!)

I

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
type(I)

numpy.ndarray

In [54]:
I[0, 0] = 1.0; I[1, 1] = 1.0; I[2, 2]=1.0 # identity matrix

x = np.array([1.0, 2.0, 3.0])   # create vector

y = np.dot(I, x)                # computes matrix-vector product

y

array([1., 2., 3.])

In [55]:
import numpy as np

I = np.eye(3)        # create identity matrix

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
type(I)             # confirm that type is ndarray

numpy.ndarray

In [57]:
I = np.matrix(I)     # convert to matrix object

In [58]:
type(I)             # confirm that type is matrix

numpy.matrix

In [59]:
x =  np.array([1., 2., 3.])   # create ndarray vetor

x =  np.matrix(x)             # convert to matrix object (row vector)

x = x.transpose()             # convert to column vector

y = I*x                      # computes matrix-vector product

y

matrix([[1.],
        [2.],
        [3.]])

Note that `np.matrix(x)` turns $x$, with type `ndarray`, into a *row* vector by default (type `matrix`), so $x$ must be transposed with `x.transpose()` before it can be multiplied with the matrix $I$.

## Random Numbers

Programming languages usually offer ways to produce (apparently) random numbers, referred to as *pseudo-random numbers*. These numbers are not truly random, since they are produced in a predictable way once a “seed” has been set (the seed is a number, which generation depends on the current time).

### Drawing One Random Number at a Time

Pseudo-random numbers come in handy if your code is to deal with phenomena characterized by some randomness.

In [60]:
import random

a = 1; b = 6
r1 = random.randint(a, b)   # first dice
r2 = random.randint(a, b)   # second dice

print('The dice gave: {:d} and {:d}'.format(r1, r2))

The dice gave: 4 and 4


The function randint is available from the imported module `random`, which is part of the standard Python library, and returns a pseudo-random integer on the interval $[a,b], a \leq b$. 

When debugging programs that involves pseudo-random number generation, it is a great advantage to *fix the seed*, which ensures that the very same sequence of numbers will generated each time the code is run. This simply means that you pick the seed yourself and tell Python what that seed should be. For our program, we could choose, e.g., 10 as our seed and insert the line
```python
random.seed(10)
```

In fact, it is a good idea to fix the seed from the outset when you write the program. Later, when (you think) it works for a fixed seed, you change it so that the
number generator sets its own seed, after which you proceed with further testing.

In [61]:
import random

random.randint(1, 6)

6

In [62]:
random.randint(1, 6)

4

In [63]:
random.seed(10)

random.randint(1, 6)

5

The `random` module contains also other useful functions, two of which are `random` (yes, same name as the module) and `uniform`. Both of these functions return a floating point number from an interval where each number has equal probability of being drawn. For `random`, the interval is always $[0,1)$ (i.e. 0 is included, but 1 is not), while `uniform` requires the programmer to specify the interval $[a, b]$ (where both a and b are included14). The functions are used similarly to `randint`, so, interactively, we may for example do:

In [64]:
import random

x = random.random()                      # draw float from [0, 1)
y = random.uniform(10, 20)               # ... float from [10, 20]

print('x = {:g}, y = {:g}'.format(x, y))

x = 0.0325851, y = 14.8256


### Drawing Many Random Numbers at a Time

If you need many pseudo-random numbers, one option is to use such function calls inside a *loop*. Another (faster) alternative, is to rather use functions that allow *vectorized drawing of the numbers*, so that a single function call provides all the numbers you need in one go. Such functionality is offered by another module, which also happens to be called `random`, but which resides in the `numpy` library. All three functions demonstrated above have their counterparts in `numpy` and we might show interactively how each of these can be used to generate, e.g., four numbers with one function call.


In [65]:
import numpy as np

np.random.randint(1, 6, 4)       #... 4 integers from [1, 6)

array([3, 4, 4, 1])

In [66]:
np.random.random(4)            # ... 4 floats from [0, 1)

array([0.33045006, 0.96272037, 0.45068438, 0.89726292])

In [67]:
np.random.uniform(10, 20, 4)  # ... 4 floats from [10, 20)

array([14.30193498, 11.13440786, 13.2172848 , 19.21039369])

One more handy function from `numpy` deserves mention. If you have an array with numbers, you can `shuffle` those numbers in a randomized way with the shuffle function,

In [68]:
import numpy as np

a = np.array([1, 2, 3, 4])

np.random.shuffle(a)

a

array([3, 1, 4, 2])

Note that also `numpy` allows the seed to be set. For example, setting the seed to 10 (as above), could be done by
```python
np.random.seed(10)
```

The fact that a module by the name random is found both in the standard Python library `random` and in `numpy`, calls for some alertness. With proper import statements, however, there should be no problem.

For more details about the numpy functions for pseudo-random numbers, check out the documentation (<https://docs.scipy.org/doc/>).