# 容器类型

容器类型用于讲对象分组汇总到一起。不同容器类型之间的最主要区别是单个元素的访问方式以及运算定义方式不同。

## 列表

顾名思义，列表是一个包含了一系列任意对象的容器：

```python
L = ['a', 20.0, 5]
M = [3, ['a',-3.0, 5]]
```
通过为每个元素分配一个索引，引用于遍历列表中的每个对象。列表第一个元素的索引值为**0**。这种基于0的索引在数学符号中经常使用。（考虑多项式系数的常用索引）

索引可用于访问如下对象：
```python
L[1]    # 返回 20.0
L[0]    # 返回 ‘a’
M[1]    # 返回['a', -3.0,5]
M[1][2] # 返回 5
```
这里的方括号用法相当于数学公式中所使用的下标。 L是一个简单的列表，而列表M本身嵌套了一个列表，以至于需要两个索引来访问嵌套列表中的元素。

通过 ``range`` 可以很容易的生成一个包含连续整数的列表

```python
L = list(range(4))    # 生成一个包含4个元素的列表： [0, 1, 2, 3]
```

更为常见的用法是为该命令提供 ``start``、``stop``、和``step``参数：

```python
L = list(range(17,29,4))   # 生成[17, 21, 25]
```

命令 ``len`` 可以返回列表的长度：
```python
len(L)   # 返回 3
```

In [1]:
L = list(range(17,29,4))
L

[17, 21, 25]

### 切片

对一个列表在 $i$ 和 $j$ 之间进行切片操作讲回生成一个新的列表，该列表包含了从索引 $i$ 开始到 $j$ 之前结束的所有元素。 

对于切片操作，必须给出索引范围。 $L[i:j]$ 意味着回截取列表 $L$ 从 $L[i]$ 开始到 $L[j-1]$ 结束的所有元素。换句话说，新的列表是通过将第$i$ 个元素从列表$L$中删除并取接下来的$j-i$个元素得到的。

**注** 
- $L[i:]$  表示删除前 $i$ 个元素，相当于截取除了前 $i$个元素之外的所有元素。
- $L[: i]$ 表示只取前$i$ 个元素，相当于截取前$i$个元素
- $L[:-i]$ 表示删除最后$i$ 个元素，相当于截取除了最后$i$个元素意外的所有元素
- $L[-i:]$ 表示只取最后$i$ 个元素，相当于截取最后$i$个元素
- $L[i:-j]$ 表示去除前$i$ 个和最后$j$元素:

In [2]:
L = ['C', 'l', 'o', 'u', 'd','s']
L[1:5]     # 删除一个元素，然后取4个

L = ['C', 'l', 'o', 'u','d', 's']
L[1:] # ['l', 'o', 'u', 'd','s']

L[:5] # ['C', 'l', 'o','u','d']

L[-2:] # ['d', 's']
L[3:-4]
L[:]

['C', 'l', 'o', 'u', 'd', 's']

Python  允许使用负数索引用于从右边计数。特别需要注意的是，元素$L[-1]$ 是列表 L的最后一个元素。 省略切片范围内的一个索引相当于实数中的半开区间。半开区间$(\infty, a)$ 表示取所有低于$a$的数字。这与语法 $L[:j]$ 类似。

**注： 越界切片**  注意在进行越界切片时，你永远不会得到索引错误，可能会得到空列表。

In [3]:
L = list(range(4)) # [0, 1, 2, 3]
L[4] # IndexError: list index out of range

IndexError: list index out of range

In [4]:
L[1:100] # same as L[1:]

[1, 2, 3]

In [5]:
L[-100:-1] # same as L[:-1]

[0, 1, 2]

In [6]:
L[-100:100] # same as L[:]

[0, 1, 2, 3]

In [7]:
L[5:0] # empty list []

[]

In [8]:
L[-2:2] # empty list []

[]

In [9]:
L[1:100]

[1, 2, 3]

在使用可能会变为负值的索引变量时应谨慎，因为它完全改变了切片，这可能会导致意想不到的结果：

In [10]:
a = [1,2,3]
for iteration in range(4):
    print(sum(a[0:iteration-1]))

3
0
1
3


## 步长

计算切片时，也可以指定步长，即从一个索引到另一个索引之间的长度。默认步长时1.

In [11]:
L = list(range(100))
L[:10:2] # [0, 2, 4, 6, 8]

[0, 2, 4, 6, 8]

In [12]:
L[::20]     # [0, 20, 40, 60, 80] 
L[10:20:3]  # [10,13,16,19]

## 步长也可能为负
L[20:10:-3] # [20,17,14,11]

[20, 17, 14, 11]

In [13]:
## 可以使用负的步长来创建一个反向的新列表
L = [1, 2, 3]
R = L[::-1] # L is not modified
print(R)

[3, 2, 1]


## 列表修改

有关列表的典型运算时插入和删除元素以及列表连接。使用切片符号让列表插入和删除变得简明易懂，删除知识用空列表$[ ]$ 来替换列表中的一部分：

In [14]:
L = ['a', 1, 2, 3, 4]
L[2:3] = [] # ['a', 1, 3, 4]
L
L[3:] = [] # ['a', 1, 3]
L

['a', 1, 3]

插入意味着要用插入的切片来替换空切片：

In [15]:
L[1:1] = [1000, 2000] # ['a', 1000, 2000, 1, 3]
L

['a', 1000, 2000, 1, 3]

两个列表通过加法运算连接起来：

In [16]:
L = [1, -17]
M = [-23.5, 18.3, 5.0]
L+M # gives [1, -17, 23.5, 18.3, 5.0]

[1, -17, -23.5, 18.3, 5.0]

将一个列表与其自身连接$n$次，我们倾向于使用乘法运算符$*$:

In [17]:
n = 3
n*[1.,17,3] # gives [1., 17, 3, 1., 17, 3, 1., 17, 3]

[1.0, 17, 3, 1.0, 17, 3, 1.0, 17, 3]

In [18]:
[0]*5 # gives [0,0,0,0,0]

[0, 0, 0, 0, 0]

列表中没有算术运算，如元素之间的求和或除法。对于这类运算，要使用数组。

## 是否属于列表

可以使用关键字in 和 not in 来确定一个元素是否属于列表，这与数学中的符号 $\in$ 和 $\notin$ 是相似的：

In [19]:
L = ['a', 1, 'b', 2]
'a' in L # True

True

In [20]:
3 in L # False

False

In [21]:
4 not in L # True

True

## 列表方法

下面表格搜集了一些有关list类型的有用方法：

命令 | 作用
:----|:----|
list.append(x)  | 将元素 x 添加至列表的末尾
list.expand(L)  | 用列表 L 的元素来扩充列表
list.insert(i,x)| 在索引 i 处插入元素 x
list.remove(x)  | 移除列表中第一个值为 x 的元素
list.count(x)   | 列表中元素 x 出现的次数
list.sort()     | 按顺序将列表中的元素进行排序
list.reverse()  | 按顺序反转列表中的元素
list.pop()      | 按顺序移除列表中的最后一个元素



列表方法有两种表现形式：
- 直接修改列表，即原位操作
- 产生一个新对象

## 原位操作

将所有的结果放入一个列表的方法都是原位操作，例如 ``reverse``

In [22]:
L = [1, 2, 3]
L.reverse() # the list L is now reversed
L # [3, 2, 1]

[3, 2, 1]

**注** 有人可能会将原位操作方法写成：

In [23]:
L=[3, 4, 4, 5]
newL = L.sort()
print(newL)

None


这在Python中是正确的，但是它可能导致你无意识地替换了列表L 并且变了 newL 的值为 None，原因是sort为原位操作。

这里演示一些原位操作方法：

In [24]:
L =  [0,1,2,3,4]
L.append(5)
L

[0, 1, 2, 3, 4, 5]

In [25]:
L.reverse()	
L

[5, 4, 3, 2, 1, 0]

In [26]:
L.sort()
L

[0, 1, 2, 3, 4, 5]

In [27]:
L.remove(0) # [1, 2, 3, 4, 5]
L

[1, 2, 3, 4, 5]

In [28]:
L.pop() # [1, 2, 3, 4]
L

[1, 2, 3, 4]

In [29]:
L.pop() # [1, 2, 3]
L

[1, 2, 3]

In [30]:
L.extend(['a','b','c']) # [1, 2, 3, a', 'b', 'c']
L

[1, 2, 3, 'a', 'b', 'c']

In [31]:
L.count(2)

1

## 列表合并 --- zip

``zip`` 是一个特别有用的列表方法。它通过把出事列表的元素配对将两个给定的列表合并为一个新的列表，其结果是一个元组列表（更多想象信息参照后面元组内容）：

In [32]:
ind = [0,1,2,3,4]
color = ["red", "green", "blue", "alpha"]
list(zip(color,ind)) # 输出为[('red', 0), ('green', 1), ('blue', 2), ('alpha', 3)]

[('red', 0), ('green', 1), ('blue', 2), ('alpha', 3)]

此事例也展示了如果两个列表长度不同所发生的情况。合并列表的长度为两个输入列表中长度较短的那个。

## 列表推导

创建列表的一个便捷方法是使用列表推导结构，其中很可能包含条件。列表推导的语法为：
```python
[<expr> for <variable> in <list>]
```
或者更常见的语法是：
```python
[<expr> for <variable> in <list> if <condition>]
```
示例如下：

In [33]:
L = [2, 3, 10, 1, 5]

L2 = [x*2 for x in L] # [4, 6, 20, 2, 10]
L2

[4, 6, 20, 2, 10]

In [34]:
L3 = [x*2 for x in L if 4 < x <= 10] # [20, 10]
L3

[20, 10]

列表推导结构中可能有多个for循环：

In [35]:
M=[[1,2,3],[4,5,6]]
flat = [M[i][j] for i in range(2) for j in range(3)] # [1, 2, 3, 4, 5, 6]
flat

[1, 2, 3, 4, 5, 6]

**注：集合符号** 列表推导与集合中的数学符号密切相关：
比较： $L_2 =\{2x: x\in L\}$ 和 ``L_2 =[2*x for x in L]``。一个很大的区别是列表是有序的，而集合不是。

# 数组

``NumPy`` 包提供了数组，数组是用于操作数学中的向量、矩阵或更高阶张量的容器结构。我们将指出数组和列表之间的相识之处，后面将进一步介绍数组的相关内容。

数组通过函数``array``从列表中构建：

In [36]:
from numpy import *
v = array([1.,2.,3.])
v

array([1., 2., 3.])

In [37]:
A = array([[1.,2.,3.],[4.,5.,6.]])
A

array([[1., 2., 3.],
       [4., 5., 6.]])

要访问一个向量的元素，需要一个索引，而矩阵的元素有两个索引来处理：

In [38]:
v[2]   # returns 3.0

3.0

In [39]:
A[1,2] # returns 6.0

6.0

形式上数组与列表类似，但是从根本上它们是不同的，这可以从以下几点解释：

- 使用方括号和切片，不仅可以访问对应于列表的数组数据，还可以用于修改数组：


In [40]:
M = array([[1.,2.],[3.,4.]])
v = array([1., 2., 3.])
v[0] # 1.

1.0

In [41]:
v[:2] # array([1.,2.])

array([1., 2.])

In [42]:
M[0,1] # 2.

2.0

In [43]:
v[:2] = [10, 20] # v is now array([10., 20., 3.])
v

array([10., 20.,  3.])

- 通过``len``函数可以获取向量中的元素数或矩阵中的行数：

In [44]:
len(v)  # 3

3

- 数组只存储相同类型的元素（通常为float 或complex，也包括 int）
- $+、*、/、-$运算符都是元素级别的。在Python 3.5及以上的版本中，dot函数和运算符$@$用于标量乘积和相应的矩阵运算。
- 与列表不同的是，数组中没有 ``append`` 方法。 另一个相关点是数组不想列表一样有弹性，我们不能使用切片来改变其长度。
- 向量切片事视图。也就是说，它们可以用于修改原始的数组。

# 元组

元组事一个不可改变的列表。不可改变意味着它不能被修改。元组知识逗号分隔的对象序列（不带括号的列表）。为了增加代码的可读性，通常将元组放在一对圆括号中：

In [45]:
my_tuple = 1, 2, 3 # our first tuple

In [46]:
my_tuple = (1, 2, 3) # the same

In [47]:
my_tuple = 1, 2, 3,  # again the same

In [48]:
len(my_tuple) # 3, same as for lists

3

In [49]:
my_tuple[0] = 'a' # error! tuples are immutable

TypeError: 'tuple' object does not support item assignment

逗号表面该对象是一个元组：

In [50]:
singleton = 1, # note the comma
len(singleton) # 1

1

当一组值需要被集合在一起时，元组是有用的。例如，它们可用于从函数返回多个值。我们可以通过拆分列表或元组来一次分配多个变量：

In [51]:
a, b = 0, 1 # a gets 0 and b gets 1
print(a)
print(b)

0
1


In [52]:
a, b = [0, 1] # exactly the same effect
(a, b) = 0, 1 # same
[a,b] = [0,1] # same thing

**交换技巧:** 可使用打包和拆分来交换两个变量的值
```python
a, b = b, a
```

元组具有如下的特点：

- 元组就是不带括号的不可变列表。
- 在多数情况下，可使用列表来代替元组。
- 没有圆括号的写法更便捷但是不安全，在不确定的时候最好使用圆括号。

In [53]:
a, b = b, a
print(a)
print(b)

1
0


In [54]:
1, 2 == 3, 4 # 返回 (1, False, 4)

(1, False, 4)

In [55]:
(1, 2) == (3, 4) # 返回  False

False

# 字典

列表、元组和数组均为对象的有序集合。根据其在列表中的位置，可以将单个对象进行插入、访问和处理。此外，字典事无序的键值对集合。我们可以通过键来访问字典数据。

## 创建和修改字典

例如可以创建一个包含力学中的刚体数据的字典，如下表示：

In [56]:
truck_wheel = {'name':'wheel','mass':5.7,
               'Ix':20.0,'Iy':1.,'Iz':17.,
               'center of mass':[0.,0.,0.]}

通过冒号： 可以表示键值对。这些键值对用逗号分隔并放在一对大括号$\{\}$中。

每个元素可以通过它们的键来访问：

In [57]:
truck_wheel['name']  # 返回 'wheel'
truck_wheel['mass']  # 返回 5.7

5.7

通过创建新的键，可以将新的对象添加到字典中：

In [58]:
truck_wheel['Ixy'] = 0.0

字典也可用于为函数提供参数。字典中的键可以有字符串、函数、具有不可变元素的元组以及类等任意一个来充当，键不能事列表或数组。命令``dict``可以用具有键值对的列表来生成一个字典：

In [59]:
truck_wheel = dict([('name','wheel'),('mass',5.7),
                     ('Ix',20.0),('Iy',1.),('Iz',17.),('center of mass',[0.,0.,0.])]) 
truck_wheel

{'name': 'wheel',
 'mass': 5.7,
 'Ix': 20.0,
 'Iy': 1.0,
 'Iz': 17.0,
 'center of mass': [0.0, 0.0, 0.0]}

## 循环遍历字典

字典的循环遍历主要有3种方式。
- 通过键的方式：

In [60]:
for key in truck_wheel.keys():
    print(key)     # 输出 

name
mass
Ix
Iy
Iz
center of mass


或者等同于如下：

In [61]:
for key in truck_wheel:
    print(key)

name
mass
Ix
Iy
Iz
center of mass


- 通过值的方式：

In [62]:
for value in truck_wheel.values():
    print(value)

wheel
5.7
20.0
1.0
17.0
[0.0, 0.0, 0.0]


- 通过元素---即键/值对的方式：

In [63]:
for item in truck_wheel.items():
    print(item)

('name', 'wheel')
('mass', 5.7)
('Ix', 20.0)
('Iy', 1.0)
('Iz', 17.0)
('center of mass', [0.0, 0.0, 0.0])


# 集合

集合是与数学中的集合一样共享属性和运算的容器。数学集合事不同对象的集合。项目事一些数学集合表达式：
$A = \{1,2,3,4\}, B ={5}, C = A \cap B, D = A \cup C, E = C\A, 5 \in C  $
以及它们所对应的Python代码

```python
A = {1,2,3,4}
B = {5}
C = A.union(B) # returns set([1,2,3,4,5])
D = A.intersection(C) # returns set([1,2,3,4])
E = C.difference(A)  # returns set([5])
5 in C # returns True
```

一个元素只能在集合中出现一次，如下事反映该定义的集合：

In [64]:
A = {1,2,3,3,3}
B = {1,2,3}
A == B # returns True

True

并且集合事无序的，也就是说，为定义集合中元素的顺序：

In [65]:
A = {1,2,3}
B = {1,3,2}
A == B # returns True

True

Python集合能够包含数值对象、字符串和布尔值。还有``union`` 和 ``intersection`` 两种方法：

In [66]:
A={1,2,3,4}
A.union({5})

{1, 2, 3, 4, 5}

In [67]:
A.intersection({2,4,6}) # returns set([2, 4])

{2, 4}

还可以使用``issubset``和``issuperset`` 两种方法来比较两个集合：

In [68]:
{2,4}.issubset({1,2,3,4,5})   # returns True

True

In [69]:
{1,2,3,4,5}.issuperset({2,4}) # returns True

True

**空集：** 在Python中，一个空集不是有$\{\}$将定义一个空字典)来定义的，而是有``empty_st = set([])`` 来定义的！

## 类型检查
查看一个变量类型的最直接方式是使用``type``命令：

In [70]:
label = 'local error'
type(label) # returns str

str

In [71]:
x = [1, 2] # list
type(x) # returns list

list

但是如果想检测一个变量是否为某种确定的类型，则应该使用``isinstance``方法(而不是用``type``命令进行类型比较)

In [72]:
isinstance(x, list) # True

True

后续学习子类和继承的概念后，使用``ininstance``的原因就显而易见了。简而言之，不同的数据类型通常与一些基本类型共享一些属性。最典型的例子就是bool类型，它是从更为通用的int类型派生而来的。

In [73]:
test = True
isinstance(test, bool) # True
isinstance(test, int) # True
type(test) == int # False
type(test) == bool # True

True

因此，为了保证变量test正好是一个整数（与特定类型不相关），应检查它是否为一个integer类型的实例：

In [74]:
if isinstance(test, int):
    print("The variable is an integer")

The variable is an integer


**类型检查** Python不是一种预定义数据类型的语言，这意味着对象是有其能做什么而不是其事什么来定义的。例如，通过使用``len``方法，你拥有了一个可以作用于某个对象的字符串操作函数，那么你的函数可能对实现该方法的任务对象都有用。